<a href="https://colab.research.google.com/github/nmagee/ds1002/blob/main/notebooks/07-numpy-continued.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Course:   DS1002
Module:   Module 5
Topic:    NumPy Continued
```

### PREREQUISITES
- import / import as
- variables

### SOURCES
- https://numpy.org/
- https://en.wikipedia.org/wiki/NumPy
- https://www.scipy.org/
- https://en.wikipedia.org/wiki/SciPy
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

### OBJECTIVES
- Introduction to Numpy

### CONCEPTS
- The numpy package contains useful functions for math operations
- The ndarray is the workhorse of the package

In [64]:
import numpy as np

# Data Types

One way to control the data type of a NumPy array is to declare it when the array is created using the `dtype` keyword argument. Take a look at the data type NumPy uses by default when creating an array with `np.zeros()`. Could it be updated?

* Using `np.zeros()`, create an array of zeros that has three rows and two columns; call it `zero_array`.  
* Print the data type of `zero_array`.


In [65]:
# Create an array of zeros with three rows and two columns
zero_array = np.zeros((3, 2))

# Print the data type of zero_array
print(zero_array.dtype)

float64


* Create a new array of zeros called `zero_int_array`, which will also have three rows and two columns, but the data type should be `np.int32`.  

* Print the data type of `zero_int_array`.

In [66]:
# Create a new array of int32 zeros with three rows and two columns
zero_int_array = np.zeros((3, 2), dtype=np.int32)

# Print the data type of zero_int_array
print(zero_int_array.dtype)

int32


In [67]:
data1 = [6, 7.5, 8, 0, 1]        # create a list
arr1 = np.array(data1)           # turn list into a numpy array
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [68]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]       # create a 2-dimensional list
arr2 = np.array(data2)                     # turn that list into a numpy array
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
arr2.ndim       # get the dimension

2

In [70]:
arr2.shape      # get the shape

(2, 4)

In [71]:
arr1.dtype      # get the data type for arr1

dtype('float64')

In [72]:
arr2.dtype      # get the data type for arr2

dtype('int64')

More Exercises

In [73]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [74]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [75]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [76]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [77]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [78]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [79]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [80]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Slicing

**Higher Dimensional Arrays**

In [81]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr2d[2]

array([7, 8, 9])

In [83]:
arr2d[0][2]

3



**Slicing: Simplified notation**

In [84]:
arr2d[0, 2]

3

A nice visual of a 2D array

<img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png" height="50%" width="50%"/>

**Two-Dimensional Array Slicing**

<img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172114.png" height="50%" width="50%"/>

**3D arrays**

In [85]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
arr3d.shape

(2, 2, 3)

In [87]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

If you find NumPy's way of showing the data a bit difficult to parse visually.

💡 **Here is a way to visualize 3 and higher dimensional data:**

```python
[ # AXIS 0                     CONTAINS 2 ELEMENTS (arrays)
    [ # AXIS 1                 CONTAINS 2 ELEMENTS (arrays)
        [1, 2, 3], # AXIS 3    CONTAINS 3 ELEMENTS (integers)
        [4, 5, 6]  # AXIS 3
    ],  
    [ # AXIS 1
        [7, 8, 9],
        [10, 11, 12]
    ]
]
```
Each axis is a level in the nested hierarchy, i.e. a tree or DAG (directed-acyclic graph).

* Each axis is a container.
* There is only one top container.
* Only the bottom containers have data.

**Omit lower indices**

In multidimensional arrays, if you omit later indices, the returned object will be a **lower-dimensional ndarray** consisting of all the data contained by the higher indexed dimension.

So in the 2 × 2 × 3 array `arr3d`:

In [88]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Saving data before modifying an array.

In [89]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Putting the data back.

In [90]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, `arr3d[1, 0]` gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array:

In [91]:
arr3d[1, 0]

array([7, 8, 9])

In [92]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [93]:
x[0]

array([7, 8, 9])

# Other Basic Array Manipulations + Calculations

NumPy has over 500 basic operations, most of which can be performed upon array data. Here are some common/obvious examples:

In [ ]:
foo = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# flip - reverse the data of an array
oof = np.flip(foo)
print(oof)

# copy - copy an array to an entirely separate array
goo = np.copy(foo)
print(goo)

# concatenate - combine all elements within an array into a single list
new_foo = np.concatenate(foo)
print(new_foo)

# min
foomin = np.min(foo)
print(foomin)

# max
foomax = np.max(foo)
print(foomax)

# mean
foomean = np.mean(foo)
print(foomean)

# sin/cos/tan
foosin = np.sin(foo)
print(foosin)

# standard deviation
foostd = np.std(foo)
print(foostd)